### ISSUE TITLE
How many frames produce a decision result?

### ISSUE THREAD

**Issue by Sun-mz** [IDKiro/action-recognition-pytorch#13]
thank you
What is the number of input frames of this network?
就是这个网络要输入几帧呢？
谢谢！

**Comment by IDKiro** [comment]
LSTM是不限制序列长度的，倒是dataloader新版本更新以后要求保持序列长度一致

**Comment by Sun-mz** [comment]
那请问这个程序在测试的时候是输入多少帧图片后进行一个判决呢？我刚弄这些,代码看的还不是很懂，是将剪切成图片之后测试文件夹下一个视频对应的文件夹内所有帧图像（比如按照您的处理数据的程序，在数据文件夹内data/valid/brush_hair/atempting_to_brush_my_hair_brush_hair_u_nm_np2_le_goo_1/这个目录下所有帧图像）都送进去之后输出一个预测结果吗？麻烦您了，谢谢！

**Comment by IDKiro** [comment]
没错，如果你不改代码的话，是会把子文件夹的所有图像都输入到网络的，稍微长一点的视频就可能爆显存。

**Comment by Sun-mz** [comment]
> 没错，如果你不改代码的话，是会把子文件夹的所有图像都输入到网络的，稍微长一点的视频就可能爆显存。

好的！知道了，非常感谢！
