### ISSUE TITLE
ImportError: cannot import name 'LSTMModel' from 'model'

### ISSUE THREAD

**Issue by Diriba01** [IDKiro/action-recognition-pytorch#4]

**Comment by Diriba01** [comment]
How to overcome the problem stated above which revealed from " from model import LSTMModel"

**Comment by IDKiro** [comment]
python version?

**Comment by Diriba01** [comment]
3.7.4

**Comment by Diriba01** [comment]
python = 3.7.4

**Comment by IDKiro** [comment]
How did you download the repo? By git clone?
Make sure that all the files are downloaded.
