### ISSUE TITLE
train_loader problem

### ISSUE THREAD

**Issue by berna-ylmz** [IDKiro/action-recognition-pytorch#7]
Hello,
I tried training with mini custom dataset(3 classes and each class contains 4 videos),and prepared _test/valid --> classname -->  frames_ hierarchy.
So I used same dataloader,but I got error this line  and it takes **too long.**
**for i, (inputs, target, _) in enumerate(train_loader):**       in training.py.

**RuntimeError: Caught RuntimeError in DataLoader worker process 0.
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 602112 bytes. Buy new RAM!**

Can you help me,please ?

Note: I used Nvidia Geforce GTX 1060
RAM :16GB

**Comment by IDKiro** [comment]
What's the duration and resolution of videos?

**Comment by berna-ylmz** [comment]
About half-hour **enumerate(train_loader)** running.And then I got the error.
resolution of videos : 1920x1080
Thanks

**Comment by IDKiro** [comment]
I think it is because your single video is too long and the resolution is too high. Because of the characteristics of LSTM, all video frames will be stored in memory and GPU memory.

**Comment by berna-ylmz** [comment]
In train.py,frame is applied transform and then size is 224. Has no effect on frame size ? 
Should I change the batch size ? What would you suggest to solve this problem?
Thanks.

**Comment by IDKiro** [comment]
If you use the dataset loader in this repo, it will resize to 224. 
How about the length of a single video and the mini batch size？
You can first set mini batch size to 1 and reduce the number of frames when converting videos to images.

**Comment by berna-ylmz** [comment]
Yes, I used datasetLoader because of same hierarchy.If I wrong please tell me.
The length of the videos is not fixed,for example one of them is 150 MB(about 18000 frames) another is 50 MB(about 13200 frames).
Batch size default value so it is 8.

**Comment by IDKiro** [comment]
I think this is the key. Each video in HMDB51 has only a few hundred frames.

**Comment by berna-ylmz** [comment]
Hımm, I tried mini batch size = 1 .But I got similar memory error.
_THCudaCheck FAIL file=..\aten\src\THC\THCCachingHostAllocator.cpp line=278 error=2 : out of memory
RuntimeError: Caught RuntimeError in pin memory thread for device 0._
You are right. As you said I will reduce number of frame,but it may not be enough.
What would you suggest if I still get the same error?

**Comment by IDKiro** [comment]
Now it is out of GPU memory, I think it will be OK if you reduce frames number. In fact, the GTX 1060's GPU memory is insufficient for this task.

**Comment by berna-ylmz** [comment]
Ok, Thanks for your help.
